### ISSUE TITLE
Creating output file from fio run

### ISSUE THREAD

**Issue by eelife** [jtulak/fio-parser#1]
Hello I am trying to run your fio from your fio-test.fio script, but because I am running on android I cannot directly pipe the output of the command to the python script. I must first save the file as a log file of some sort then pull that into my ubuntu PC and then run the python script.

Can you help me create the log file (or the .out file) that the python script requires, when I ran it simply using the --minimal command i created dozens of "test-multi-file-io-x.x.xx" files, how do I take these and create something the python script can work with?

**Comment by jtulak** [comment]
So, what is your issue? You can't run the script directly because you don't have Python on Android?
In any case, ``fio test.fio --minimal | ./fio-parser.py`` will give you the same result as these two commands: ``fio test.fio --minimal > logfile`` and `` ./fio-parser.py --input logfile``. The test-multi-file-io... files can be ignored.

Let me know if this is what you need.

**Comment by eelife** [comment]
That was exactly what I was looking for. Thanks! However, now I am trying to understand the output file. it looks like this. 
[output_file.txt](https://github.com/jtulak/fio-parser/files/1148600/output_file.txt)

Is there a way to obtain information about latency or bandwidth. I see in your readme this is possible. Should I just try to work through the python script, or this information available?

**Comment by jtulak** [comment]
Sure. Look at ``libfioparser/FioJob.py`` and ``libfioparser/RWStatus.py`` for what fields are implemented and simply change the ``parse()`` function in ``fio-parser.py`` to what you want. The printed result is an example of how to use it and it already prints read/write bandwidth.

(If the field you want is not there for some reason, even though fio produces the number, you will have to add a new field into these two files. But I think I implemented them all. Latencies certainly are there.)

**Comment by eelife** [comment]
okay that makes sense. But could you quickly specify the units of the r/w bandwidth column?

**Comment by jtulak** [comment]
I think it should be in basic units (B, IOps, ...), but I didn't use it for some time to be sure. You can easily find it out - either it is the same as what fio produces (see https://linux.die.net/man/1/fio Terse Output section), or it is in basic units. And you can always change it into what you need in ``parse()``.
